name: Run Firebase Calculator

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-calculator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin

    - name: Set up Firebase Credentials
      run: |
        echo "$FIREBASE_CREDENTIALS" > firebase_creds.json
        cat firebase_creds.json  # Debug: Show content (remove this in production)
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

    - name: Run Firebase Calculator Script
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}  # Ensure it is available
      run: python fire.py
